In [69]:
from torch import Tensor
from torchvision import transforms
from torch.utils.data import DataLoader, Dataset
from torchvision.datasets import CIFAR10
from torch.utils.data.distributed import DistributedSampler
import os
from PIL import Image

class RealBlur(Dataset):
    def __init__(self,data_path):
        scenes = os.listdir(data_path)
        self.path_images = []
        self.path_gts = []
        for scence in scenes:
            path = os.path.join(data_path,scence)
            blur_path = os.path.join(path,'blur')
            gt_path = os.path.join(path,'gt')
            images = os.listdir(blur_path)
            gt = os.listdir(gt_path)
            for idx,_ in enumerate(images):
                self.path_images.append(os.path.join(blur_path,images[idx]))
                self.path_gts.append(os.path.join(gt_path,gt[idx]))
        self.trans = transforms.Compose([
            transforms.Resize((256,256)),
#             transforms.RandomCrop(224),
            transforms.ToTensor(),
            transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5)),
        ])
        self.path_images = sorted(self.path_images)
        self.path_gts = sorted(self.path_gts)

    def __len__(self):
        return len(self.path_images)

    def __getitem__(self,idx):
        image = Image.open(self.path_images[idx])
        gt = Image.open(self.path_gts[idx])
        image = self.trans(image)
        gt = self.trans(gt)
        return image


def load_data(batchsize:int, numworkers:int, data_path:str = None) -> DataLoader:
    data_train = RealBlur(data_path)
    # sampler = DistributedSampler(data_train)
    trainloader = DataLoader(
                        data_train,
                        batch_size = batchsize,
                        num_workers = numworkers
                        # sampler = sampler,
                        # drop_last = True
                    )
    return trainloader

def transback(data:Tensor) -> Tensor:
    return data / 2 + 0.5


In [70]:
data_train = RealBlur('RealBlur-Tele/RealBlur-J-Tele_ECC_IMCORR_centroid_itensity_ref/')
trainloader = DataLoader(
                        data_train,
                        batch_size = 16,
                        num_workers = 4
                        # sampler = sampler,
                        # drop_last = True
                    )

In [71]:
for a in trainloader:
    print(a)

tensor([[[[-0.9922, -0.9922, -0.9922,  ..., -0.9922, -0.9922, -0.9922],
          [-0.9922, -0.9922, -0.9922,  ..., -0.9922, -0.9922, -0.9922],
          [-0.9843, -0.9922, -0.9922,  ..., -0.9922, -0.9922, -0.9922],
          ...,
          [-0.9922, -0.9922, -0.9843,  ..., -0.9922, -0.9922, -0.9922],
          [-0.9922, -0.9922, -0.9843,  ..., -0.9922, -0.9922, -0.9922],
          [-0.9843, -0.9843, -0.9843,  ..., -0.9922, -0.9922, -0.9922]],

         [[-0.9843, -0.9843, -0.9922,  ..., -0.9843, -0.9922, -0.9922],
          [-0.9843, -0.9843, -0.9843,  ..., -0.9843, -0.9922, -0.9843],
          [-0.9843, -0.9843, -0.9922,  ..., -0.9843, -0.9843, -0.9843],
          ...,
          [-0.9922, -0.9922, -0.9843,  ..., -0.9922, -0.9922, -0.9922],
          [-0.9922, -0.9922, -0.9922,  ..., -0.9922, -0.9922, -0.9843],
          [-0.9843, -0.9843, -0.9843,  ..., -0.9843, -0.9922, -0.9843]],

         [[-0.9843, -0.9922, -0.9843,  ..., -0.9922, -0.9922, -0.9922],
          [-0.9843, -0.9843, -

tensor([[[[-0.7490, -0.8039, -0.8431,  ..., -0.5529, -0.5529, -0.5294],
          [-0.7412, -0.7725, -0.8275,  ..., -0.5451, -0.5608, -0.5451],
          [-0.7569, -0.7882, -0.8196,  ..., -0.5216, -0.5529, -0.5373],
          ...,
          [-0.0039,  0.0667,  0.1137,  ..., -0.6471, -0.6471, -0.6549],
          [ 0.0667,  0.1137,  0.1529,  ..., -0.6471, -0.6549, -0.6549],
          [ 0.1137,  0.1608,  0.2078,  ..., -0.6549, -0.6627, -0.6706]],

         [[-0.4510, -0.5137, -0.5843,  ..., -0.5843, -0.5765, -0.5608],
          [-0.4667, -0.5216, -0.6000,  ..., -0.5686, -0.5843, -0.5686],
          [-0.5059, -0.5608, -0.6157,  ..., -0.5451, -0.5765, -0.5608],
          ...,
          [-0.0667, -0.0118,  0.0431,  ..., -0.6549, -0.6549, -0.6627],
          [-0.0039,  0.0431,  0.0824,  ..., -0.6627, -0.6627, -0.6627],
          [ 0.0431,  0.0980,  0.1294,  ..., -0.6706, -0.6627, -0.6627]],

         [[-0.4824, -0.5294, -0.5843,  ..., -0.9373, -0.9294, -0.9216],
          [-0.5216, -0.5529, -

tensor([[[[-0.3882, -0.3490, -0.3569,  ..., -0.4275, -0.4353, -0.4431],
          [-0.4039, -0.3647, -0.3961,  ..., -0.4275, -0.4275, -0.4431],
          [-0.4118, -0.3647, -0.3647,  ..., -0.4275, -0.4275, -0.4353],
          ...,
          [-0.0980, -0.1137, -0.0902,  ..., -0.6000, -0.6392, -0.6627],
          [ 0.0275,  0.0118, -0.0039,  ..., -0.6784, -0.7020, -0.7098],
          [ 0.0824,  0.0745,  0.0353,  ..., -0.5922, -0.6000, -0.6000]],

         [[-0.2078, -0.1294, -0.1529,  ..., -0.8196, -0.8196, -0.8196],
          [-0.2314, -0.1608, -0.1922,  ..., -0.8118, -0.8196, -0.8196],
          [-0.2471, -0.1765, -0.1922,  ..., -0.8118, -0.8196, -0.8196],
          ...,
          [-0.3490, -0.3647, -0.3569,  ..., -0.6471, -0.6706, -0.6863],
          [-0.2314, -0.2471, -0.2549,  ..., -0.7020, -0.7176, -0.7333],
          [-0.1686, -0.1686, -0.2000,  ..., -0.6627, -0.6706, -0.6784]],

         [[ 0.0431,  0.1294,  0.0824,  ..., -0.5608, -0.5608, -0.5686],
          [-0.0039,  0.0745,  

tensor([[[[-0.1922, -0.1216, -0.1137,  ...,  0.1373,  0.1294,  0.1216],
          [-0.1686, -0.0824, -0.0902,  ...,  0.1373,  0.1294,  0.1294],
          [-0.1451, -0.0667, -0.0745,  ...,  0.1294,  0.1216,  0.1294],
          ...,
          [ 0.1922,  0.2471,  0.2549,  ..., -0.3804, -0.3569, -0.3804],
          [ 0.2157,  0.2471,  0.2549,  ..., -0.2941, -0.2784, -0.3020],
          [ 0.2157,  0.2392,  0.2471,  ..., -0.2157, -0.1922, -0.2157]],

         [[-0.1059, -0.0118,  0.0039,  ...,  0.2314,  0.2157,  0.2314],
          [-0.0745,  0.0275,  0.0275,  ...,  0.2235,  0.2000,  0.2471],
          [-0.0510,  0.0431,  0.0431,  ...,  0.2157,  0.1843,  0.2627],
          ...,
          [ 0.3176,  0.3647,  0.3725,  ..., -0.0824, -0.0824, -0.1137],
          [ 0.3412,  0.3647,  0.3725,  ..., -0.0196, -0.0196, -0.0510],
          [ 0.3412,  0.3569,  0.3725,  ...,  0.0275,  0.0275,  0.0039]],

         [[ 0.1686,  0.2706,  0.2863,  ...,  0.4902,  0.4745,  0.4902],
          [ 0.1922,  0.3098,  

tensor([[[[-0.8980, -0.8824, -0.8588,  ..., -0.9294, -0.9294, -0.9294],
          [-0.6078, -0.5922, -0.5686,  ..., -0.9294, -0.9294, -0.9294],
          [-0.4039, -0.4431, -0.4510,  ..., -0.9294, -0.9216, -0.9294],
          ...,
          [-0.7647, -0.7647, -0.7647,  ..., -0.8039, -0.7961, -0.8039],
          [-0.7647, -0.7647, -0.7647,  ..., -0.8118, -0.8118, -0.8118],
          [-0.7725, -0.7725, -0.7725,  ..., -0.8039, -0.7961, -0.7961]],

         [[-0.9059, -0.8980, -0.8824,  ..., -0.9294, -0.9294, -0.9294],
          [-0.6549, -0.6392, -0.6235,  ..., -0.9294, -0.9294, -0.9294],
          [-0.4431, -0.4588, -0.4667,  ..., -0.9294, -0.9294, -0.9294],
          ...,
          [-0.8275, -0.8275, -0.8353,  ..., -0.8510, -0.8431, -0.8431],
          [-0.8275, -0.8353, -0.8353,  ..., -0.8588, -0.8588, -0.8588],
          [-0.8353, -0.8353, -0.8431,  ..., -0.8588, -0.8588, -0.8588]],

         [[-0.8667, -0.8588, -0.8431,  ..., -0.8667, -0.8667, -0.8667],
          [-0.6078, -0.5922, -

tensor([[[[-0.5373, -0.6706, -0.8196,  ..., -0.0275,  0.0196,  0.0588],
          [-0.5686, -0.6314, -0.7725,  ..., -0.0275,  0.0118,  0.0431],
          [-0.6157, -0.6157, -0.7333,  ..., -0.0275,  0.0039,  0.0353],
          ...,
          [-0.2941, -0.2549, -0.2235,  ..., -0.7490, -0.7490, -0.7490],
          [-0.3804, -0.3412, -0.2314,  ..., -0.7412, -0.7490, -0.7490],
          [-0.4510, -0.4667, -0.3490,  ..., -0.7412, -0.7490, -0.7490]],

         [[-0.6706, -0.7647, -0.8745,  ..., -0.5294, -0.4667, -0.4275],
          [-0.7098, -0.7490, -0.8431,  ..., -0.5294, -0.4588, -0.4118],
          [-0.7412, -0.7412, -0.8196,  ..., -0.5294, -0.4667, -0.4275],
          ...,
          [-0.5451, -0.5137, -0.4902,  ..., -0.7569, -0.7569, -0.7569],
          [-0.6078, -0.5765, -0.4980,  ..., -0.7490, -0.7569, -0.7569],
          [-0.6627, -0.6863, -0.5922,  ..., -0.7490, -0.7569, -0.7647]],

         [[-0.7569, -0.8275, -0.9059,  ..., -0.8353, -0.7569, -0.7176],
          [-0.7961, -0.8275, -

tensor([[[[-0.7490, -0.7490, -0.7569,  ..., -0.7882, -0.8039, -0.8118],
          [-0.7490, -0.7176, -0.7255,  ..., -0.7882, -0.8118, -0.8196],
          [-0.7255, -0.7176, -0.7412,  ..., -0.8118, -0.8039, -0.8196],
          ...,
          [-0.8275, -0.8196, -0.8118,  ..., -0.8118, -0.8196, -0.8118],
          [-0.8353, -0.8196, -0.8118,  ..., -0.8353, -0.8275, -0.8118],
          [-0.8275, -0.8118, -0.8039,  ..., -0.8275, -0.8196, -0.8118]],

         [[-0.8588, -0.8667, -0.8588,  ..., -0.8824, -0.8980, -0.8980],
          [-0.8667, -0.8510, -0.8431,  ..., -0.8824, -0.8980, -0.9059],
          [-0.8588, -0.8510, -0.8510,  ..., -0.8980, -0.8902, -0.8980],
          ...,
          [-0.9059, -0.8980, -0.9059,  ..., -0.8824, -0.8902, -0.8824],
          [-0.9059, -0.8980, -0.9059,  ..., -0.8902, -0.8902, -0.8824],
          [-0.8980, -0.9059, -0.8980,  ..., -0.8902, -0.8824, -0.8902]],

         [[-0.8824, -0.8980, -0.8902,  ..., -0.9059, -0.9216, -0.9294],
          [-0.9059, -0.8902, -

tensor([[[[-0.7333, -0.6863, -0.6706,  ..., -0.4196, -0.4039, -0.5451],
          [-0.7412, -0.7020, -0.6784,  ..., -0.4039, -0.3882, -0.5216],
          [-0.7490, -0.7098, -0.6784,  ..., -0.4039, -0.3804, -0.5137],
          ...,
          [-0.4902, -0.4745, -0.4902,  ..., -0.6157, -0.6000, -0.6000],
          [-0.4745, -0.4745, -0.4745,  ..., -0.6078, -0.6078, -0.6078],
          [-0.4667, -0.4588, -0.4588,  ..., -0.6157, -0.6235, -0.6235]],

         [[-0.8275, -0.8275, -0.8431,  ..., -0.5373, -0.5294, -0.6392],
          [-0.8510, -0.8431, -0.8510,  ..., -0.5373, -0.5216, -0.6235],
          [-0.8510, -0.8510, -0.8510,  ..., -0.5216, -0.5059, -0.6000],
          ...,
          [-0.7098, -0.6941, -0.7020,  ..., -0.7647, -0.7647, -0.7569],
          [-0.6941, -0.6863, -0.6863,  ..., -0.7647, -0.7725, -0.7647],
          [-0.6863, -0.6706, -0.6706,  ..., -0.7725, -0.7725, -0.7804]],

         [[-0.8980, -0.8980, -0.9137,  ..., -0.6549, -0.6471, -0.7255],
          [-0.9059, -0.9059, -

tensor([[[[-0.8275, -0.8353, -0.8353,  ..., -0.9216, -0.9137, -0.9137],
          [-0.8353, -0.8353, -0.8353,  ..., -0.9137, -0.9216, -0.9216],
          [-0.8353, -0.8353, -0.8353,  ..., -0.9216, -0.9137, -0.9216],
          ...,
          [-0.0510, -0.0431, -0.0431,  ..., -0.2627, -0.2941, -0.3333],
          [-0.0510, -0.0510, -0.0431,  ..., -0.2706, -0.3176, -0.3490],
          [-0.0588, -0.0588, -0.0353,  ..., -0.2863, -0.3255, -0.3490]],

         [[-0.2471, -0.2471, -0.2392,  ..., -0.4353, -0.4431, -0.4431],
          [-0.2471, -0.2471, -0.2392,  ..., -0.4353, -0.4431, -0.4431],
          [-0.2471, -0.2471, -0.2392,  ..., -0.4353, -0.4431, -0.4431],
          ...,
          [-0.0588, -0.0510, -0.0431,  ..., -0.1294, -0.1922, -0.2392],
          [-0.0588, -0.0588, -0.0510,  ..., -0.1608, -0.2157, -0.2627],
          [-0.0588, -0.0588, -0.0510,  ..., -0.1765, -0.2235, -0.2706]],

         [[-0.1216, -0.1059, -0.1059,  ..., -0.3647, -0.3725, -0.3725],
          [-0.1137, -0.1137, -

tensor([[[[-0.8039, -0.8039, -0.8118,  ..., -0.0588, -0.0275,  0.0510],
          [-0.8353, -0.8275, -0.8118,  ..., -0.0196,  0.0039,  0.1059],
          [-0.8588, -0.8353, -0.8275,  ...,  0.0118,  0.0275,  0.1059],
          ...,
          [-0.1216, -0.1294, -0.1137,  ..., -0.1294, -0.1294, -0.0980],
          [-0.3412, -0.3098, -0.2235,  ..., -0.1216, -0.0980, -0.0745],
          [-0.5294, -0.4980, -0.4275,  ..., -0.1137, -0.0980, -0.0824]],

         [[-0.6392, -0.6471, -0.6627,  ...,  0.1059,  0.1294,  0.2000],
          [-0.6784, -0.6706, -0.6471,  ...,  0.1451,  0.1529,  0.2549],
          [-0.7098, -0.6784, -0.6706,  ...,  0.1686,  0.1765,  0.2471],
          ...,
          [-0.0431, -0.0510, -0.0431,  ..., -0.0667, -0.0510, -0.0039],
          [-0.2627, -0.2314, -0.1608,  ..., -0.0510, -0.0196,  0.0118],
          [-0.4824, -0.4588, -0.3725,  ..., -0.0431, -0.0118,  0.0196]],

         [[-1.0000, -1.0000, -1.0000,  ...,  0.2314,  0.1922,  0.2314],
          [-1.0000, -1.0000, -

tensor([[[[-0.0510, -0.0353, -0.0039,  ...,  0.4353,  0.4431,  0.3961],
          [-0.0588, -0.0431, -0.0039,  ...,  0.4588,  0.4353,  0.3176],
          [-0.0667, -0.0431, -0.0039,  ...,  0.4667,  0.3569,  0.1686],
          ...,
          [-0.3176, -0.3255, -0.3333,  ..., -0.2706, -0.2784, -0.0824],
          [-0.3255, -0.3176, -0.3333,  ..., -0.2392, -0.3020, -0.1216],
          [-0.3333, -0.3333, -0.3333,  ..., -0.2000, -0.3176, -0.1686]],

         [[-0.2863, -0.2784, -0.2549,  ..., -0.0039,  0.0118, -0.0196],
          [-0.2941, -0.2863, -0.2549,  ...,  0.0196,  0.0118, -0.0980],
          [-0.3098, -0.2941, -0.2627,  ...,  0.0510, -0.0510, -0.2392],
          ...,
          [-0.4902, -0.4902, -0.4980,  ..., -0.5373, -0.5373, -0.3882],
          [-0.4902, -0.4902, -0.4980,  ..., -0.5137, -0.5529, -0.4196],
          [-0.4980, -0.5059, -0.5059,  ..., -0.4902, -0.5686, -0.4431]],

         [[-0.6549, -0.6471, -0.6314,  ..., -0.6392, -0.6157, -0.6392],
          [-0.6471, -0.6471, -

tensor([[[[-0.3647, -0.3333, -0.3255,  ...,  0.9294,  0.9373,  0.9373],
          [-0.3569, -0.3333, -0.3176,  ...,  0.8824,  0.9059,  0.9137],
          [-0.3490, -0.3255, -0.3176,  ...,  0.7882,  0.8431,  0.8745],
          ...,
          [ 0.1529,  0.3725,  0.5529,  ..., -0.4431, -0.4353, -0.4353],
          [ 0.2863,  0.4824,  0.6235,  ..., -0.4431, -0.4431, -0.4353],
          [ 0.3255,  0.5059,  0.6314,  ..., -0.4510, -0.4588, -0.4588]],

         [[-0.1529, -0.1373, -0.1216,  ...,  0.9294,  0.9373,  0.9451],
          [-0.1451, -0.1373, -0.1216,  ...,  0.8980,  0.9137,  0.9294],
          [-0.1529, -0.1294, -0.1137,  ...,  0.8353,  0.8824,  0.9059],
          ...,
          [ 0.2314,  0.4431,  0.6157,  ..., -0.5373, -0.5373, -0.5373],
          [ 0.3647,  0.5451,  0.6863,  ..., -0.5451, -0.5451, -0.5451],
          [ 0.4118,  0.5686,  0.7020,  ..., -0.5686, -0.5686, -0.5686]],

         [[-0.1922, -0.1843, -0.1686,  ...,  0.9137,  0.9216,  0.9216],
          [-0.1922, -0.1765, -

tensor([[[[-0.2157, -0.2157, -0.2000,  ..., -0.5608, -0.5608, -0.5529],
          [-0.5059, -0.4902, -0.4824,  ..., -0.5529, -0.5529, -0.5451],
          [-0.5529, -0.5529, -0.5451,  ..., -0.5529, -0.5529, -0.4980],
          ...,
          [ 0.2000,  0.1843,  0.1765,  ..., -0.7412, -0.7176, -0.7098],
          [ 0.2235,  0.2078,  0.2078,  ..., -0.7333, -0.7255, -0.7176],
          [ 0.2392,  0.2314,  0.2235,  ..., -0.7333, -0.7255, -0.7176]],

         [[-0.2157, -0.2157, -0.2078,  ..., -0.4196, -0.3882, -0.3255],
          [-0.5059, -0.4902, -0.4824,  ..., -0.4118, -0.3882, -0.3255],
          [-0.5529, -0.5529, -0.5451,  ..., -0.4039, -0.3725, -0.2863],
          ...,
          [ 0.1137,  0.0980,  0.0902,  ..., -0.6706, -0.6392, -0.6157],
          [ 0.1373,  0.1294,  0.1216,  ..., -0.6627, -0.6471, -0.6314],
          [ 0.1529,  0.1529,  0.1373,  ..., -0.6627, -0.6392, -0.6314]],

         [[-0.2941, -0.3020, -0.2863,  ..., -0.4588, -0.4275, -0.3647],
          [-0.5608, -0.5608, -

KeyboardInterrupt: 